FROM node:16

# The working directory inside your container
WORKDIR /home/$HOST_USER/FarmData2

# copy package.json to the working directory
COPY package*.json ./

# This will install those dependencies
RUN npm install

# Copy the rest of the app to the working directory
COPY . /home/$HOST_USER/FarmData2

# Run the container
CMD ["npm", "start"]